"""Example: Ensemble-based calibration of Arno basin using pestpp-ies.

This script demonstrates the IES (Iterative Ensemble Smoother) workflow:
1. Load calibration configuration
2. Set up PEST++ working directory for IES
3. Run pestpp-ies (ensemble generated automatically by pestpp-ies)

Prerequisites:
    - Install calibration dependencies and PEST++ binaries:
        make install-calib
            or (manually)
        pip install mobidicpy[calibration] && get-pestpp :pyemu
    - Ensure preprocessed simulation data is available (gisdata.nc, network.parquet)
"""

from pathlib import Path

from mobidic.calibration import (
    PestSetup,
    load_calibration_config,
)
from mobidic.calibration.config import CalibrationConfig

# Load calibration config and switch to IES
calib_config_path = Path(__file__).parent / "calibration.yaml"
cc = load_calibration_config(calib_config_path)

# Set specific options for IES
cc_dict = cc.model_dump()
cc_dict["pest_tool"] = "ies"  # Override tool to IES
cc_dict["pest_options"] = {"noptmax": 5, "ies_num_reals": 50}

cc_ies = CalibrationConfig(**cc_dict)

# Set up PEST++
pest = PestSetup(cc_ies, base_path=calib_config_path.parent)
working_dir = pest.setup()

print(f"\nPEST++ IES working directory created: {working_dir}")

# Run pestpp-ies
# Ensemble is automatically generated by pestpp-ies
results = pest.run(num_workers=4)

# # Analyze ensemble results
# ens_results = results.get_ensemble_results()
# if ens_results:
#     prior = ens_results.get("prior_parameters")
#     posterior = ens_results.get("posterior_parameters")
