"""PestSetup orchestrator: creates PEST++ working directory and runs calibration.

This module builds the complete PEST++ setup from a CalibrationConfig:
- Generates template (.tpl) and instruction (.ins) files
- Builds the PEST control file (.pst) via pyemu
- Generates the forward model runner script
- Optionally runs the initial forward run
- Executes PEST++ (local or cluster mode)
"""

from __future__ import annotations

import json
import os
import shutil
import warnings
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
from loguru import logger

from mobidic.calibration.config import CalibrationConfig, load_calibration_config

if TYPE_CHECKING:
    from mobidic.calibration.results import CalibrationResults
from mobidic.calibration.forward_model import generate_forward_run_script
from mobidic.calibration.instruction import generate_instruction_file
from mobidic.calibration.observation import align_observations_to_simulation, load_observations
from mobidic.calibration.template import generate_model_input_csv, generate_template_file

# Suppress pyemu warning about missing flopy (not needed for PEST++ calibration)
warnings.filterwarnings("ignore", message="Failed to import legacy module", module="pyemu")

# PEST++ tool name mapping to executable names
PEST_TOOL_MAP = {
    "glm": "pestpp-glm",
    "ies": "pestpp-ies",
    "sen": "pestpp-sen",
    "da": "pestpp-da",
    "opt": "pestpp-opt",
    "mou": "pestpp-mou",
    "sqp": "pestpp-sqp",
}


class PestSetup:
    """Orchestrator for PEST++ calibration of MOBIDICpy.

    Creates a complete PEST++ working directory with all necessary files
    and provides methods to execute calibration.

    Args:
        calib_config: Calibration configuration (CalibrationConfig object or path to YAML).
        base_path: Base directory for resolving relative paths in the config.
    """

    def __init__(self, calib_config: CalibrationConfig | str | Path, base_path: Path | None = None):
        if isinstance(calib_config, (str, Path)):
            config_path = Path(calib_config)
            self.calib_config = load_calibration_config(config_path)
            self.base_path = base_path or config_path.parent
        else:
            self.calib_config = calib_config
            self.base_path = base_path or Path.cwd()

        self._pest_exe = PEST_TOOL_MAP[self.calib_config.pest_tool]
        self._working_dir = None
        self._obs_data = None  # Cached observation alignment data
        self._n_obs_per_group = None

    @property
    def working_dir(self) -> Path:
        """Path to the PEST++ working directory."""
        if self._working_dir is None:
            wd = Path(self.calib_config.working_dir)
            if not wd.is_absolute():
                wd = self.base_path / wd
            self._working_dir = wd
        return self._working_dir

    def setup(self) -> Path:
        """Create complete PEST++ working directory with all files.

        Returns:
            Path to the working directory.
        """

        cc = self.calib_config
        wd = self.working_dir

        logger.info(f"Setting up PEST++ working directory: {wd}")

        # Create working directory
        wd.mkdir(parents=True, exist_ok=True)

        # Resolve MOBIDIC config path
        mobidic_config_path = Path(cc.mobidic_config)
        if not mobidic_config_path.is_absolute():
            mobidic_config_path = self.base_path / mobidic_config_path

        # Load MOBIDIC config to get paths
        from mobidic.config import load_config

        mobidic_config = load_config(mobidic_config_path)
        gisdata_path = Path(mobidic_config.paths.gisdata)
        network_path = Path(mobidic_config.paths.network)

        # Determine forcing path
        if mobidic_config.paths.meteoraster:
            forcing_path = Path(mobidic_config.paths.meteoraster)
        elif cc.use_raster_forcing:
            # Will be generated by initial forward run
            forcing_path = wd / "forcing_raster.nc"
        else:
            forcing_path = Path(mobidic_config.paths.meteodata)

        # Determine calibration period (controls which observations are used)
        if cc.calibration_period:
            calib_start = cc.calibration_period.start_date
            calib_end = cc.calibration_period.end_date
        else:
            # Use first/last observation time
            all_obs = []
            for obs_group in cc.observations:
                obs_df = load_observations(obs_group, self.base_path)
                all_obs.append(obs_df)
            all_times = pd.concat(all_obs)["time"]
            calib_start = str(all_times.min())
            calib_end = str(all_times.max())

        # Determine simulation period (the full window the forward model runs,
        # including warm-up). Defaults to calibration period if not specified.
        if cc.simulation_period:
            sim_start = cc.simulation_period.start_date
            sim_end = cc.simulation_period.end_date
        else:
            sim_start = calib_start
            sim_end = calib_end

        # Validate simulation period against forcing time range
        self._validate_calibration_period(forcing_path, mobidic_config, sim_start, sim_end)

        # Run initial forward run if raster forcing needs generation
        if cc.use_raster_forcing and not forcing_path.exists():
            logger.info("Running initial forward run to generate raster forcing...")
            self._run_initial_forward(mobidic_config_path, mobidic_config, forcing_path, sim_start, sim_end)

        # Load observations and align to simulation timesteps
        # Observations are filtered to calibration period, but aligned to the
        # full simulation time grid (so sim_indices are correct)
        self._load_and_align_observations(sim_start, sim_end, calib_start, calib_end, mobidic_config)

        # Check if routing parameters are being calibrated
        routing_keys = {"parameters.routing.wcel", "parameters.routing.Br0", "parameters.routing.NBr"}
        routing_calibrated = any(p.parameter_key in routing_keys for p in cc.parameters)

        # 1. Generate template file
        generate_template_file(cc, wd / "model_input.csv.tpl")

        # 2. Generate initial model_input.csv
        generate_model_input_csv(cc, wd / "model_input.csv")

        # 3. Generate instruction file
        ins_path, obs_names = generate_instruction_file(cc, self._n_obs_per_group, wd / "model_output.csv.ins")

        # 4. Generate forward model runner script
        obs_data_json = json.dumps(self._obs_data)
        observation_reaches = [og.reach_id for og in cc.observations]

        generate_forward_run_script(
            base_config_path=mobidic_config_path,
            gisdata_path=gisdata_path,
            network_path=network_path,
            forcing_path=forcing_path,
            start_date=sim_start,
            end_date=sim_end,
            observation_reaches=observation_reaches,
            obs_data_json=obs_data_json,
            routing_params_calibrated=routing_calibrated,
            output_script_path=wd / "forward_run.py",
        )

        # 5. Build PEST control file via pyemu
        pst = self._build_pst(obs_names, wd)

        # Write .pst file
        pst_path = wd / "calibration.pst"
        pst_version = self.calib_config.pest_options.get("pst_version", 2)
        pst.write(str(pst_path), version=pst_version)
        logger.info(f"PEST control file written: {pst_path} (version={pst_version})")

        logger.success(f"PEST++ setup complete in {wd}")
        return wd

    def run(self, num_workers: int | None = None, start_manager: bool = True) -> "CalibrationResults":
        """Execute PEST++ with parallel workers.

        Args:
            num_workers: Override number of workers (default: from config or os.cpu_count()).
            start_manager: If True (default), start the manager on this machine (local mode).
                If False, start agents only for cluster mode.

        Returns:
            CalibrationResults with parsed output.
        """
        import pyemu

        cfg = self.calib_config.parallel
        n_workers = num_workers or cfg.num_workers or os.cpu_count()
        is_cluster = cfg.manager_ip is not None and not start_manager

        wd = self.working_dir

        # Create a clean template directory containing only PEST files (no subdirectories).
        # This prevents recursive directory nesting: if worker_dir == worker_root, pyemu
        # copies the growing directory into each new worker, causing exponential growth.
        template_dir = wd / "_template"
        if template_dir.exists():
            shutil.rmtree(template_dir)
        template_dir.mkdir()
        for f in wd.iterdir():
            if f.is_file():
                shutil.copy2(f, template_dir / f.name)

        if is_cluster:
            logger.info(f"Starting {n_workers} PEST++ agents connecting to {cfg.manager_ip}:{cfg.port}")
            pyemu.os_utils.start_workers(
                worker_dir=str(template_dir),
                exe_rel_path=self._pest_exe,
                pst_rel_path="calibration.pst",
                num_workers=n_workers,
                worker_root=str(wd),
                port=cfg.port,
                master_dir=None,
                local=cfg.manager_ip,
            )
        else:
            logger.info(f"Starting PEST++ ({self._pest_exe}) with {n_workers} local workers")
            pyemu.os_utils.start_workers(
                worker_dir=str(template_dir),
                exe_rel_path=self._pest_exe,
                pst_rel_path="calibration.pst",
                num_workers=n_workers,
                worker_root=str(wd),
                port=cfg.port,
                master_dir=str(wd / "master"),
                local=True,
            )

        # Clean up template directory
        shutil.rmtree(template_dir, ignore_errors=True)

        return self.load_results()

    def load_results(self) -> "CalibrationResults":
        """Load results from a completed PEST++ run.

        Returns:
            CalibrationResults parsed from PEST++ output files.
        """
        from mobidic.calibration.results import CalibrationResults

        master_dir = self.working_dir / "master"
        if not master_dir.exists():
            master_dir = self.working_dir

        return CalibrationResults.from_pest_output(
            master_dir=master_dir,
            calib_config=self.calib_config,
        )

    def _load_and_align_observations(
        self,
        sim_start: str,
        sim_end: str,
        calib_start: str,
        calib_end: str,
        mobidic_config,
    ) -> None:
        """Load all observations and align to simulation time grid.

        Observations are filtered to the calibration period but aligned to the
        full simulation time grid so that sim_indices correctly reference
        positions in the forward model output (which runs the full simulation).

        Populates self._obs_data and self._n_obs_per_group.
        """
        dt = mobidic_config.simulation.timestep
        sim_times = pd.date_range(start=sim_start, end=sim_end, freq=f"{int(dt)}s")

        self._obs_data = []
        self._n_obs_per_group = {}

        for obs_group in self.calib_config.observations:
            # Filter observations to calibration period (not simulation period)
            obs_df = load_observations(obs_group, self.base_path, calib_start, calib_end)
            # Align to full simulation time grid
            sim_indices, obs_values, obs_times = align_observations_to_simulation(obs_df, sim_times)

            n_obs = len(sim_indices)
            self._n_obs_per_group[obs_group.name] = n_obs

            obs_info = {
                "name": obs_group.name,
                "reach_id": obs_group.reach_id,
                "n_obs": n_obs,
                "sim_indices": sim_indices.tolist(),
                "obs_values": obs_values.tolist(),
            }

            if obs_group.metrics:
                obs_info["metrics"] = [
                    {"metric": m.metric, "target": m.target, "weight": m.weight} for m in obs_group.metrics
                ]

            self._obs_data.append(obs_info)

            logger.info(f"Observation group '{obs_group.name}': {n_obs} matched observations")

    def _build_pst(self, obs_names: list[str], wd: Path):
        """Build the PEST control file (.pst) using pyemu.

        Args:
            obs_names: List of all observation names.
            wd: Working directory.

        Returns:
            pyemu.Pst object.
        """
        import pyemu

        cc = self.calib_config

        # Build parameter data
        par_data = []
        par_groups = set()
        for p in cc.parameters:
            par_groups.add(p.par_group)
            par_data.append(
                {
                    "parnme": p.name,
                    "partrans": p.transform if p.transform != "fixed" else "fixed",
                    "parchglim": "factor",
                    "parval1": p.initial_value,
                    "parlbnd": p.lower_bound,
                    "parubnd": p.upper_bound,
                    "pargp": p.par_group,
                    "scale": p.scale,
                    "offset": p.offset,
                    "dercom": 1,
                }
            )
        par_df = pd.DataFrame(par_data)
        par_df.index = par_df["parnme"]

        # Build observation data
        obs_data = []
        obs_name_set = set()

        for obs_group in cc.observations:
            n_obs = self._n_obs_per_group.get(obs_group.name, 0)
            obs_info = next((d for d in self._obs_data if d["name"] == obs_group.name), None)
            obs_values = obs_info["obs_values"] if obs_info else []

            # Time-series observations
            for i in range(n_obs):
                obs_name = f"{obs_group.name}_{i:04d}"
                obs_val = obs_values[i] if i < len(obs_values) else 0.0
                obs_data.append(
                    {
                        "obsnme": obs_name,
                        "obsval": obs_val,
                        "weight": obs_group.weight,
                        "obgnme": obs_group.name,
                    }
                )
                obs_name_set.add(obs_name)

            # Metric pseudo-observations
            if obs_group.metrics:
                for mc in obs_group.metrics:
                    obs_name = f"{obs_group.name}_{mc.metric}"
                    obs_data.append(
                        {
                            "obsnme": obs_name,
                            "obsval": mc.target,
                            "weight": mc.weight,
                            "obgnme": f"{obs_group.name}_metrics",
                        }
                    )
                    obs_name_set.add(obs_name)

        obs_df = pd.DataFrame(obs_data)
        obs_df.index = obs_df["obsnme"]

        # Create Pst object
        pst = pyemu.Pst.from_par_obs_names(
            par_names=par_df.index.tolist(),
            obs_names=obs_df.index.tolist(),
        )

        # Update parameter data
        pst.parameter_data.loc[par_df.index, "partrans"] = par_df["partrans"]
        pst.parameter_data.loc[par_df.index, "parchglim"] = par_df["parchglim"]
        pst.parameter_data.loc[par_df.index, "parval1"] = par_df["parval1"]
        pst.parameter_data.loc[par_df.index, "parlbnd"] = par_df["parlbnd"]
        pst.parameter_data.loc[par_df.index, "parubnd"] = par_df["parubnd"]
        pst.parameter_data.loc[par_df.index, "pargp"] = par_df["pargp"]
        pst.parameter_data.loc[par_df.index, "scale"] = par_df["scale"]
        pst.parameter_data.loc[par_df.index, "offset"] = par_df["offset"]
        pst.parameter_data.loc[par_df.index, "dercom"] = par_df["dercom"]

        # Update observation data
        pst.observation_data.loc[obs_df.index, "obsval"] = obs_df["obsval"]
        pst.observation_data.loc[obs_df.index, "weight"] = obs_df["weight"]
        pst.observation_data.loc[obs_df.index, "obgnme"] = obs_df["obgnme"]

        # Set model command
        pst.model_command = ["python forward_run.py"]

        # Set template and instruction file pairs
        pst.model_input_data = pd.DataFrame(
            {
                "pest_file": ["model_input.csv.tpl"],
                "model_file": ["model_input.csv"],
            }
        )
        pst.model_output_data = pd.DataFrame(
            {
                "pest_file": ["model_output.csv.ins"],
                "model_file": ["model_output.csv"],
            }
        )

        # Set control data from pest_options (with defaults)
        control_data_keys = {"noptmax", "relparmax", "facparmax"}
        pst.control_data.noptmax = cc.pest_options.get("noptmax", 20)
        pst.control_data.relparmax = cc.pest_options.get("relparmax", 10.0)
        pst.control_data.facparmax = cc.pest_options.get("facparmax", 10.0)
        pst.svd_data.maxsing = len(cc.parameters)

        # Apply additional PEST++ options (skip keys already handled as control_data)
        for key, value in cc.pest_options.items():
            if key in control_data_keys or key == "pst_version":
                continue
            pst.pestpp_options[key] = value

        logger.info(
            f"Built PEST control file: {len(cc.parameters)} parameters, "
            f"{len(obs_data)} observations, tool={self._pest_exe}"
        )
        return pst

    def _validate_calibration_period(self, forcing_path: Path, mobidic_config, start_date: str, end_date: str) -> None:
        """Validate that the simulation period is contained within the forcing time range.

        The simulation period (which includes any warm-up before the calibration
        window) must fit within the available forcing data so that PEST++ forward
        runs can actually be executed.

        Args:
            forcing_path: Path to forcing NetCDF file.
            mobidic_config: Loaded MOBIDICConfig object.
            start_date: Simulation start date string.
            end_date: Simulation end date string.

        Raises:
            ValueError: If the simulation period extends outside the forcing data range.
        """
        sim_start = pd.Timestamp(start_date)
        sim_end = pd.Timestamp(end_date)

        # Determine the forcing time range
        forcing_start = None
        forcing_end = None

        if forcing_path.exists():
            # Load just enough to get the time range (MeteoRaster or MeteoData)
            try:
                from mobidic.preprocessing.meteo_raster import MeteoRaster

                forcing = MeteoRaster.from_netcdf(forcing_path, preload=False)
                forcing_start = forcing.start_date
                forcing_end = forcing.end_date
            except Exception:
                try:
                    from mobidic.preprocessing.meteo_preprocessing import MeteoData

                    forcing = MeteoData.from_netcdf(forcing_path)
                    forcing_start = forcing.start_date
                    forcing_end = forcing.end_date
                except Exception:
                    logger.warning(
                        f"Could not determine forcing time range from {forcing_path}. "
                        "Skipping calibration period validation."
                    )
                    return
        elif not self.calib_config.use_raster_forcing:
            # Forcing file should exist if we're not generating it
            logger.warning(f"Forcing file not found: {forcing_path}. Skipping calibration period validation.")
            return
        else:
            # Raster forcing will be generated — skip validation (it will use the simulation period)
            return

        if forcing_start is None or forcing_end is None:
            return

        # Check: simulation start_date >= forcing start_date
        if sim_start < forcing_start:
            raise ValueError(
                f"Simulation start_date ({start_date}) is before the forcing data start "
                f"({forcing_start}). The simulation period must be contained within the "
                f"available forcing data period."
            )

        # Check: simulation end_date <= forcing end_date
        if sim_end > forcing_end:
            raise ValueError(
                f"Simulation end_date ({end_date}) is after the forcing data end "
                f"({forcing_end}). The simulation period must be contained within the "
                f"available forcing data period."
            )

        logger.info(
            f"Simulation period validated: [{start_date}, {end_date}] is within "
            f"forcing period [{forcing_start}, {forcing_end}]"
        )

    def _run_initial_forward(self, config_path, config, forcing_path, start_date, end_date):
        """Run initial forward simulation to generate raster forcing."""
        from mobidic.core.simulation import Simulation
        from mobidic.preprocessing.io import load_gisdata
        from mobidic.preprocessing.meteo_preprocessing import MeteoData

        gisdata = load_gisdata(config.paths.gisdata, config.paths.network)

        # Enable meteo output so interpolated forcing is saved as raster
        config.output_forcing_data.meteo_data = True

        forcing = MeteoData.from_netcdf(config.paths.meteodata)
        sim = Simulation(gisdata, forcing, config)
        sim.run(start_date, end_date)

        # Copy the generated meteo_forcing.nc to the expected forcing_path
        output_dir = Path(config.paths.output)
        meteo_output = output_dir / "meteo_forcing.nc"
        if meteo_output.exists():
            shutil.copy2(meteo_output, forcing_path)
            logger.info(f"Rasterized forcing saved to {forcing_path}")
        else:
            raise FileNotFoundError(f"Expected rasterized forcing at {meteo_output} but not found")
