name: fair-software

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Check FAIR compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check FAIR software compliance
        uses: fair-software/howfairis-github-action@0.2.1
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
